version: '3.8'
services:
  #  db:
  #    image: postgres
  bot-engine:
    build: ./the_bot_engine
    volumes:
      - ./runtime:/runtime
    ports:
      - "8100:8100"
    environment:
      - hokan.runtime.profile=
  bot-io:
    build: ./the_bot_io
    volumes:
      - ./runtime:/runtime
    ports:
      - "8090:8090"
    environment:
      - hokan.runtime.profile=
